name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.x
                  include-prerelease: true

            - name: Publish Application
              run: dotnet publish src/Website.Personal.Client/Website.Personal.Client.csproj -c Release -o release --nologo

            # base href url value should be changed so that resources like CSS and scripts can load properly. 
            - name: Rewrite base href
              if: success()
              uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
              with:
                html_path: ${{ env.PUBLISH_DIR }}/index.html
                base_href: BASE_URL or REPOSITORY_NAME
